# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'

steps:
# - task: DockerCompose@0
#   inputs:
#     containerregistrytype: 'Container Registry'
#     dockerComposeFile: '**/docker-compose.yml'
#     action: 'Run a Docker Compose command'
#     dockerComposeCommand: 'build'
# - task: DockerCompose@0
#   inputs:
#     containerregistrytype: 'Container Registry'
#     dockerComposeFile: '**/docker-compose.yml'
#     action: 'Run a Docker Compose command'
#     dockerComposeCommand: 'up --exit-code-from tests-php7'
#- task: DockerCompose@0
#  inputs:
#    containerregistrytype: 'Container Registry'
#    dockerComposeFile: '**/docker-compose.yml'
#    action: 'Run a Docker Compose command'
#    dockerComposeCommand: 'up --exit-code-from tests-php5'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Tests/Dockerfile'
    buildContext: './'